# Generated by Django 4.0.5 on 2023-07-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='info',
            field=models.TextField(default=' ', verbose_name='info'),
        ),
    ]
